// src/components/Roller/Roller.tsx
import React, { useState } from 'react';
import { useForm } from '../../customHooks';

function Roller() {
    // TODO WRAP THIS ALL UP SOMEWHERE ELSE
    const endpoint = 'http://localhost:4567/roll/';
    const buttonClicked = () => {
        console.log(`Rolling ${input}...`)
        fetch(endpoint + input)
            .then(response => response.json())
            .then(data => setResults(results.concat(data.result)))
    }
    const { input, handleInputChange, handleSubmit } = useForm(buttonClicked);
    const [results, setResults] = useState([]);

    return (
        <div>
            <form onSubmit={handleSubmit}>
                <label>
                    Roll:
                <input onChange={handleInputChange} type="text" value={input} />
                </label>
                <button type="submit">Roll!</button>
            </form>
            <ul>
                {results.map((r, i) => <li key={i}>{r}</li>).reverse()}
            </ul>
        </div>
    )
}

export default Roller;

// src/components/Roller.svelte
<div>
  <label>
    Roll:
  <input placeholder="1d6" bind:value={input_text} />
  </label>
  <button on:click {buttonClicked}>Roll!</button>
  <ul>
      {#each results as { total, base, modifier }}
        <li>
          <span class="roll-total">{total}</span> (<span class="roll-base">{base}</span>
          +
          <span class="roll-modifier">{modifier}</span>)
        </li>
      {/each}
  </ul>
</div>

<style>
</style>

<script>
export let results = []
export let input_text = "";
export const buttonClicked = (_) => {
    console.log(`Rolling ${input}...`)
    fetch(endpoint + input)
        .then(response => response.json())
        .then(data => results.push(data))
}

</script>
